In [11]:
# https://deeplearningcourses.com/c/deep-learning-advanced-nlp
from __future__ import print_function, division
from builtins import range, input
# Note: you may need to update your version of future
# sudo pip install -U future

from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

import keras.backend as K

In [6]:
T = 8 # t tane time step olacak
D = 2 # her time stepe giren oznitellik vektorunun boyutu
M = 3 # lstm hücresinin ağırlık matrisinin boyutu

In [15]:
data = np.random.randn(1,T,D)

In [16]:
data

array([[[-0.02841764, -1.09113959],
        [ 2.28232171, -0.68889252],
        [-0.20249317,  0.05276723],
        [ 0.74401367, -0.34785084],
        [-0.24985871, -0.03780174],
        [ 0.15956984, -0.06990336],
        [-0.18036725,  1.09108597],
        [ 0.11006348, -0.42655369]]])

In [21]:
def lstm1():
    input_ = Input(shape=(T, D))
    rnn = LSTM(M, return_state=True)
    
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o , h, c = model.predict(data)
    
    print("o:", o)
    print("h:", h)
    print("c:", c)

In [22]:
lstm1()

o: [[ 0.01972121 -0.07622948 -0.05682108]]
h: [[ 0.01972121 -0.07622948 -0.05682108]]
c: [[ 0.0362429  -0.14638871 -0.1128479 ]]


In [23]:
def lstm2():
    input_ = Input(shape=(T, D))
    rnn = LSTM(M, return_state=True, return_sequences=True)
    
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h, c = model.predict(data)
    
    print("o:", o)
    print("h:", h)
    print("c:", c)

In [24]:
lstm2()

o: [[[-0.08114209 -0.14214274 -0.08218926]
  [ 0.02384127  0.04328049  0.06182485]
  [ 0.01149886  0.01716667  0.08011347]
  [-0.00054923  0.04273032  0.12150884]
  [-0.02383766 -0.00715027  0.06857187]
  [-0.0213      0.00508332  0.06780134]
  [ 0.03433961  0.12202879  0.09212343]
  [-0.02031998  0.01183021  0.04342412]]]
h: [[-0.02031998  0.01183021  0.04342412]]
c: [[-0.0445527   0.02525242  0.08965096]]


In [27]:
def gru1():
    input_ = Input(shape=(T, D))
    rnn = GRU(M, return_state=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h = model.predict(data)
    print("o:", o)
    print("h:", h)

In [28]:
gru1()

o: [[ 0.02557967  0.00472661 -0.00956878]]
h: [[ 0.02557967  0.00472661 -0.00956878]]


In [29]:
def gru2():
    input_ = Input(shape=(T, D))
    rnn = GRU(M, return_state=True, return_sequences=True)
    x = rnn(input_)

    model = Model(inputs=input_, outputs=x)
    o, h = model.predict(data)
    print("o:", o)
    print("h:", h)

In [30]:
gru2()

o: [[[ 0.2015297  -0.1563578   0.31344157]
  [ 0.02879117  0.2336666   0.56758326]
  [ 0.11533238  0.08642614  0.21710616]
  [ 0.03877586  0.10379539  0.27077228]
  [ 0.10855984 -0.00403122  0.09690922]
  [ 0.06098944  0.00515877  0.06272668]
  [-0.1386663   0.16729318 -0.20153648]
  [-0.05685478  0.06095742  0.08996349]]]
h: [[-0.05685478  0.06095742  0.08996349]]
